version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
      - "automated"
    open-pull-requests-limit: 5
    reviewers:
      - "YK0317"
    assignees:
      - "YK0317"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5
    reviewers:
      - "YK0317"
    assignees:
      - "YK0317"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 3 