version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://taskcafe:${DB_PASSWORD:-password}@db:5432/taskcafe?sslmode=disable
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret_change_me}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3333}
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - app-uploads:/root/uploads

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=taskcafe
      - POSTGRES_USER=taskcafe
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskcafe"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  app-uploads:
